first_time = true
first_time_desc = """
Тут была абоба.
"""

[[tasks]]
name = "Привет, мир!"
desc = """
В этой задаче Вам предстоит создать новый 
Git репозиторий и сделать в нём первый коммит.
"""
extended_desc = [
"Давайте начнём с чего-нибудь лёгкого.",
"Создайте в папке \"hello-world\" новый Git репозиторий, в котором напишите код на C, выводящий на экран строчку \"Hello, World!\".",
"После этого сделайте ровно один коммит, добавляющий этот код, с названием \"Initial commit\"."
]
work_name = "hello-world"
dir = "basics"
status = "in_progress"
