first_time = true 
first_time_desc = """
Тут была абоба.
"""

[[tasks]]
name = "Привет, мир!"
desc = """
В этой задаче Вам предстоит создать новый 
Git репозиторий и сделать в нём первый коммит.
"""
work_name = "hello-world"
dir = "basics"
status = "in_progress"

[[tasks]]
name = "Абоба"
desc = """
a
"""
work_name="ab"
dir="a"
status="approved"
